//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestModel", Namespace="http://schemas.datacontract.org/2004/07/MRS.Helper.Models")]
    public partial class RequestModel : object
    {
        
        private string AdditionalDataField;
        
        private long AutoChargeReferenceNumberField;
        
        private System.Nullable<byte> BankIdField;
        
        private string CardNumberField;
        
        private string CellNumberField;
        
        private int ChargeTypeField;
        
        private int DeviceTypeField;
        
        private long ExternalReferenceNumberField;
        
        private System.DateTime LocalDateTimeField;
        
        private string NationalCodeField;
        
        private short OperatorIdField;
        
        private string OtherNumberField;
        
        private string PasswordField;
        
        private long ReferenceNumberField;
        
        private long ReserveNumberField;
        
        private System.Nullable<long> TerminalIdField;
        
        private decimal TotalAmountField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AutoChargeReferenceNumber
        {
            get
            {
                return this.AutoChargeReferenceNumberField;
            }
            set
            {
                this.AutoChargeReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> BankId
        {
            get
            {
                return this.BankIdField;
            }
            set
            {
                this.BankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNumber
        {
            get
            {
                return this.CellNumberField;
            }
            set
            {
                this.CellNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChargeType
        {
            get
            {
                return this.ChargeTypeField;
            }
            set
            {
                this.ChargeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExternalReferenceNumber
        {
            get
            {
                return this.ExternalReferenceNumberField;
            }
            set
            {
                this.ExternalReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LocalDateTime
        {
            get
            {
                return this.LocalDateTimeField;
            }
            set
            {
                this.LocalDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode
        {
            get
            {
                return this.NationalCodeField;
            }
            set
            {
                this.NationalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OperatorId
        {
            get
            {
                return this.OperatorIdField;
            }
            set
            {
                this.OperatorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherNumber
        {
            get
            {
                return this.OtherNumberField;
            }
            set
            {
                this.OtherNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReserveNumber
        {
            get
            {
                return this.ReserveNumberField;
            }
            set
            {
                this.ReserveNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TerminalId
        {
            get
            {
                return this.TerminalIdField;
            }
            set
            {
                this.TerminalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckServerReponse", Namespace="http://schemas.datacontract.org/2004/07/MRS.Helper.Models")]
    public partial class CheckServerReponse : object
    {
        
        private string BalanceAmountField;
        
        private string DescriptionField;
        
        private System.Nullable<bool> MCIField;
        
        private System.Nullable<bool> MTNField;
        
        private int ReturnCodeField;
        
        private System.Nullable<bool> RightelField;
        
        private System.Nullable<bool> ShatelField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BalanceAmount
        {
            get
            {
                return this.BalanceAmountField;
            }
            set
            {
                this.BalanceAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MCI
        {
            get
            {
                return this.MCIField;
            }
            set
            {
                this.MCIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MTN
        {
            get
            {
                return this.MTNField;
            }
            set
            {
                this.MTNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Rightel
        {
            get
            {
                return this.RightelField;
            }
            set
            {
                this.RightelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Shatel
        {
            get
            {
                return this.ShatelField;
            }
            set
            {
                this.ShatelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModel", Namespace="http://schemas.datacontract.org/2004/07/MRS.Helper.Models")]
    public partial class ResponseModel : object
    {
        
        private string AdditionalDataField;
        
        private int ChargeTypeField;
        
        private string DescriptionField;
        
        private System.DateTime LocalDateTimeField;
        
        private string OperatorField;
        
        private long ReferenceNumberField;
        
        private long ReserveNumberField;
        
        private int ReturnCodeField;
        
        private string ReturnMsgField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChargeType
        {
            get
            {
                return this.ChargeTypeField;
            }
            set
            {
                this.ChargeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LocalDateTime
        {
            get
            {
                return this.LocalDateTimeField;
            }
            set
            {
                this.LocalDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operator
        {
            get
            {
                return this.OperatorField;
            }
            set
            {
                this.OperatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReserveNumber
        {
            get
            {
                return this.ReserveNumberField;
            }
            set
            {
                this.ReserveNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsg
        {
            get
            {
                return this.ReturnMsgField;
            }
            set
            {
                this.ReturnMsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordReqModel", Namespace="http://schemas.datacontract.org/2004/07/MRS.Helper.Models")]
    public partial class PasswordReqModel : object
    {
        
        private string NewPasswordField;
        
        private int OtpField;
        
        private string PasswordField;
        
        private ServiceReference.PasswordRequestType RequestTypeField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword
        {
            get
            {
                return this.NewPasswordField;
            }
            set
            {
                this.NewPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Otp
        {
            get
            {
                return this.OtpField;
            }
            set
            {
                this.OtpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.PasswordRequestType RequestType
        {
            get
            {
                return this.RequestTypeField;
            }
            set
            {
                this.RequestTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordRequestType", Namespace="http://schemas.datacontract.org/2004/07/MRS.Helper.Models")]
    public enum PasswordRequestType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetOtp = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangePassword = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IChargeSrv")]
    public interface IChargeSrv
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/CheckServer", ReplyAction="http://tempuri.org/IChargeSrv/CheckServerResponse")]
        System.Threading.Tasks.Task<ServiceReference.CheckServerReponse> CheckServerAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/ReserveCharge", ReplyAction="http://tempuri.org/IChargeSrv/ReserveChargeResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> ReserveChargeAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/Approve", ReplyAction="http://tempuri.org/IChargeSrv/ApproveResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> ApproveAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/ChechRequest", ReplyAction="http://tempuri.org/IChargeSrv/ChechRequestResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> ChechRequestAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/CheckBalance", ReplyAction="http://tempuri.org/IChargeSrv/CheckBalanceResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> CheckBalanceAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/CheckRequest", ReplyAction="http://tempuri.org/IChargeSrv/CheckRequestResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> CheckRequestAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/ReverseRequest", ReplyAction="http://tempuri.org/IChargeSrv/ReverseRequestResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> ReverseRequestAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/SimCardInquiry", ReplyAction="http://tempuri.org/IChargeSrv/SimCardInquiryResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> SimCardInquiryAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/ReserveSimCard", ReplyAction="http://tempuri.org/IChargeSrv/ReserveSimCardResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> ReserveSimCardAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/ReserveInternetPackage", ReplyAction="http://tempuri.org/IChargeSrv/ReserveInternetPackageResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> ReserveInternetPackageAsync(ServiceReference.RequestModel req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeSrv/PasswordManager", ReplyAction="http://tempuri.org/IChargeSrv/PasswordManagerResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponseModel> PasswordManagerAsync(ServiceReference.PasswordReqModel req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    public interface IChargeSrvChannel : ServiceReference.IChargeSrv, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    public partial class ChargeSrvClient : System.ServiceModel.ClientBase<ServiceReference.IChargeSrv>, ServiceReference.IChargeSrv
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ChargeSrvClient() : 
                base(ChargeSrvClient.GetDefaultBinding(), ChargeSrvClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IChargeSrv.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChargeSrvClient(EndpointConfiguration endpointConfiguration) : 
                base(ChargeSrvClient.GetBindingForEndpoint(endpointConfiguration), ChargeSrvClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChargeSrvClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ChargeSrvClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChargeSrvClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ChargeSrvClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChargeSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CheckServerReponse> CheckServerAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.CheckServerAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> ReserveChargeAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.ReserveChargeAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> ApproveAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.ApproveAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> ChechRequestAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.ChechRequestAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> CheckBalanceAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.CheckBalanceAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> CheckRequestAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.CheckRequestAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> ReverseRequestAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.ReverseRequestAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> SimCardInquiryAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.SimCardInquiryAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> ReserveSimCardAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.ReserveSimCardAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> ReserveInternetPackageAsync(ServiceReference.RequestModel req)
        {
            return base.Channel.ReserveInternetPackageAsync(req);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponseModel> PasswordManagerAsync(ServiceReference.PasswordReqModel req)
        {
            return base.Channel.PasswordManagerAsync(req);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IChargeSrv))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IChargeSrv))
            {
                return new System.ServiceModel.EndpointAddress("https://echarge.mobtakerancell.com/TopUp/ChargeSrv.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ChargeSrvClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IChargeSrv);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ChargeSrvClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IChargeSrv);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IChargeSrv,
        }
    }
}
